///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Configuration MP Guide
:description: Helidon configuration
:keywords: helidon, configuration, microprofile, guide

This guide describes how to create a sample MicroProfile (MP) project
that can be used to run some basic examples using both built-in and custom configuration with Helidon MP.

== What you need

[width=50%,role="flex, sm7"]
|===
|About 30 minutes
|<<about/03_prerequisites.adoc,Helidon Prerequisites>>
|===

=== Create a sample Helidon MP project

Use the Helidon MP Maven archetype to create a simple project that can be used for the examples in this guide.

[source,bash,subs="attributes+"]
.Run the Maven archetype:
----
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp
----

=== Configuration sources

You can configure Helidon to read configuration data from a variety of sources, and in several formats.  Helidon
will parse and merge all sources into an in-memory tree which represents the configuration’s structure and values.

Here is the list of external config sources.  Inclusion and precedence of all of these source can be controlled programmatically,
as will be discussed later in this guide:

1. Java system properties - the property is a name/value pair.
2. Environment variables - the property is a name/value pair.
3. Resources in the classpath - the contents of the resource is parsed according to its inferred format.
4. File - the contents of the file is parsed according to its inferred format.
5. Directory - each non-directory file in the directory becomes a config entry: the file name is the key
and the contents of that file are used as the corresponding config String value.
6. A URL resource - contents is parsed according to its inferred format.


====  Source precedence using external configuration

By default, Helidon will use the following sources in precedence order:

1. Java system properties
2. Environment variables
3. Properties specified in `META-INF/microprofile-config.properties`

Each of these sources specify configuration properties in key/value pair, like `color=red'. If any of the Helidon
required properties are not specified in one of these source, then Helidon will use a default value.

The following example will demonstrate this precedence order.  Since environment variable names are restricted to
alphanumeric characters and underscore, the name must be modified.

NOTE: Helidon adds aliases to this configuration source that enable setting or overriding config entries
with dotted and/or hyphenated keys.The mapping makes it possible to set or override a config entry with
a key of "foo.bar" using an environment variable named "FOO_BAR" and "foo.bar-baz" using "FOO_BAR_dash_BAZ".
Later examples will demonstrate this.  See <<config/06_advanced-configuration,Advance Configuration>> for more information.

[source,java]
.Update the `GreetingProvider` class and change app.greeting to appGreeting:
----
    public GreetingProvider(@ConfigProperty(name = "appGreeting") String message) {
----

[source,bash]
.Update the META-INF/microprofile-config.properties` resource and change app.greeting to appGreeting
----
appGreeting=Hello
----

[source,bash]
.Build the application, skipping unit tests, then run it:
----
mvn package -DskipTests=true
java -jar target/helidon-quickstart-mp.jar
----

[source,bash]
.Run the curl command in a new terminal window:
----
curl http://localhost:8080/greet
----

[source,json]
.JSON response:
----
{
  "message": "Hello World!" // <1>
}
----
<1> The `appGreeting` value in `META-INF/microprofile-config.properties` is used.

=====  Environment variable override

An environment variable is the second highest level of precedence over any other configuration source.

[source,bash]
.Set the environment variable, start the server then run the test:
----
export appGreeting=HelloFromEnvironment
java -jar target/helidon-quickstart-mp.jar
...
(in a different terminal window)
curl http://localhost:8080/greet
----

[source,json]
.JSON response:
----
{
  "message": "HelloFromEnvironment World!" // <1>
}
----
<1> The environment variable took precedence over  `META-INF/microprofile-config.properties` .

=====  System property override

A system property has the highest level of precedence over any other configuration source.

[source,bash]
.Run the test with a system property.  The `appGreeting` environment variable is still set:
----
java -DappGreeting="HelloFromSystemProperty"  -jar target/helidon-quickstart-mp.jar

(in a different terminal window)
curl http://localhost:8080/greet
----

[source,json]
.JSON response:
----
{
  "message": "HelloFromSystemProperty World!" // <1>
}
----
<1> The system property took precedence over both the environment variable and `META-INF/microprofile-config.properties`.

=====  System property override


====  Source precedence using code


=== Classpath sources

The following example demonstrates how to add a second internal configuration resource that is discovered in the `classpath`.
The code needs to build a `Config` object, which in turn is used to build the `Server` object.  The `Config` object is built using a `Config.Builder`,
which lets you inject any number of sources into the builder.  Furthermore, you can set precedence for the sources.
The first source has highest precedence, then the next has second highest, and so forth.  This is true for all sources, regardless of the type.

Add a second resource file, named `config.properties` to the `resources` folder with the following content:

[source,text]
.`resources/config.properties`
----
app.greeting=Hi
----

[source,java]
.Update the `Main` class; 1) Add imports, 2) replace the `startServer` method, 3) add the `buildConfig` method:
----
import io.helidon.config.Config;
import static io.helidon.config.ConfigSources.classpath;
...

    static Server startServer() {
        return Server.builder()
                .config(buildConfig()) // <1>
                .build()
                .start();
    }

    private static Config buildConfig() {
        return Config.builder()
            .sources(
                classpath("config.properties"), // <2>
                classpath("META-INF/microprofile-config.properties")) // <3>
            .build();
    }

----
<1> Pass the custom `Config` object to the `Server.Builder`.
<2> Specify the new config.properties resource that is in the `classpath`.  It has the highest precedence of any source.
<3> Specify the existing `META-INF/microprofile-config.properties` that is also in the `classpath` (see note below).

NOTE: When you use a custom `Config` object, you are responsible for specifying all resources,
even the default `META-INF/microprofile-config.properties` resource.


[source,bash]
.Build and run the application, then invoke the endpoint below:
----
curl http://localhost:8080/greet
----

[source,json]
.JSON response:
----
{
  "message": "Hi World!" // <1>
}
----
<1> The greeting was picked up from `config.properties`, overriding the value in `META-INF/microprofile-config.properties`.

NOTE: It is important to remember that configuration from all sources get merged internally.  If you have the same
 configuration property in multiple sources then only the one with highest precedence will be used at runtime.
This is true even the same property comes from sources with different formats.

=== External file sources

=== URL sources


==== Meta-configuration

, you can  prepare meta-configuration in a file that declares the sources to load and their attributes.

You can either specify the meta-config file in your application or allow the config system to search for and load meta-config from a preset list of possible sources.

You can use an external file as a configuration source and mark it as optional.  By default, any specified external source is mandatory,
if it is missing, your application will not start.  The following example will demonstrate this.

[source,java]
.Replace the `Main.buildConfig` method with the following:
----
    private static Config buildConfig() {
        return Config.builder()
            .sources(
                file("missing"),  // <1>
                classpath("config.properties"),
                classpath("META-INF/microprofile-config.properties"))
            .build();
    }
----
<1> Specifiy a file configuration source that doesn't exist.


[source,bash]
.Build and run the application.  You should see the following exception:
----
Exception in thread "main" io.helidon.config.ConfigException: Cannot load data from mandatory source FileConfig[missing]. File 'missing' not found.
----

This can be fixed by making the file optional.

[source,java]
.Replace the `Main.buildConfig` method with the following:
----
    private static Config buildConfig() {
        return Config.builder()
            .sources(
                file("missing").optional(), // <1>
                classpath("config.properties"),
                classpath("META-INF/microprofile-config.properties"))
            .build();
    }
----
<1> This file is now optional.

[source,bash]
.Build and run the application, then invoke the endpoint below:
----
curl http://localhost:8080/greet
----

[source,json]
.JSON response:
----
{
  "message": "Hi World!" // <1>
}
----
<1> The greeting was picked up from `config.properties` since the source file `missing` was not found.

=== Configuration Formats


=== Accessing Configuration within an application


=== Integration with Kubernetes

The following example shows how to integrate the Helidon MP application with Kubernetes.

[source,bash]
.Stop the application and build the docker image:
----
docker build -t helidon-configuration-mp .
----

[source,yaml]
.Create the Kubernetes YAML specification, named `config.yaml`, with the following content:
----
kind: Service
apiVersion: v1
metadata:
  name: helidon-configuration // <1>
  labels:
    app: helidon-configuration
  annotations:
    prometheus.io/scrape: 'true' // <2>
spec:
  type: NodePort
  selector:
    app: helidon-configuration
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helidon-configuration
spec:
  replicas: 1 // <3>
  template:
    metadata:
      labels:
        app: helidon-configuration
        version: v1
    spec:
      containers:
        - name: helidon-configuration
          image: helidon-configuration-mp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
----
<1> A service of type `NodePort` that serves the default routes on port `8080`.
<2> An annotation that will allow Prometheus to discover and scrape the application pod.
<3> A deployment with one replica of a pod.


[source,bash]
.Create and deploy the application into Kubernetes:
----
kubectl apply -f ./config.yaml
----

[source,bash]
.Get the service information:
----
kubectl get service/helidon-configuration
----

[source,bash]
----
NAME             TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
helidon-configuration   NodePort   10.99.159.2   <none>        8080:31143/TCP   8s // <1>
----
<1> A service of type `NodePort` that serves the default routes on port `31143`.

[source,bash]
.Verify the configuration endpoint using port `30116`, your port will likely be different:
----
curl http://localhost:31143/configuration
----

You can now delete the Kubernetes resources that were just created during this example.

[source,bash]
.Delete the application Kubernetes resources:
----
kubectl delete -f ./config.yaml
----

=== Summary

This guide demonstrated how to use configuration in a Helidon MP application using various combinations of
sources and formats:

* A

Refer to the following references for additional information:

* <<about/01_introduction.adoc,Helidon Configuration>>
* Helidon Javadoc at https://helidon.io/docs/latest/apidocs/index.html?overview-summary.html

